### ISSUE TITLE
Why Empty?

### ISSUE THREAD

**Issue by SebKrantz** [KevinKotze/sarb2015q3#1]
Hi @KevinKotze, thanks for the great effort in maintaining SARB vintages down to 2012. I'm just processing those to get vintage datasets for a SA nowcasting paper we want to write. But I see this one is missing...

**Comment by KevinKotze** [comment]
Hi Sebastian,

Unfortunately, SARB did not provide that specific dataset on their previous
website. At one stage I did start to capture the data from the quarterly
bulletin, but that project has now been shelved until the end of the
semester.

With kind regards,

Kevin

**Comment by SebKrantz** [comment]
Thanks! Ok, we'll see how to deal with that. But yeah getting the other data from your repo's worked very well. Going forward, the QB is also included in SAMADB, so we'll also be generating new vintages here (https://github.com/Stellenbosch-Econometrics/SAMADB/tree/main/datasources/quarterly_bulletin). But for historical coverage your project is really great, and having vintages as repos is of course much easier to access accessing them through the version history of one repo. So thanks again.
